export const UPDATE_OFFICE = 'UPDATE_OFFICE';

export const UPDATE_VACANCIES = 'UPDATE_VACANCIES';
export const UPDATE_VACANCIES_DICTIONARY = 'UPDATE_VACANCIES_DICTIONARY';
export const UPDATE_VACANCIES_PAGINATION = 'UPDATE_VACANCIES_PAGINATION';

export const UPDATE_DIRECTIONS = 'UPDATE_DIRECTIONS';
export const UPDATE_DIRECTIONS_PAGINATION = 'UPDATE_DIRECTIONS_PAGINATION';

export const GET_ANSWER_FORM = 'GET_ANSWER_FORM';

export const UPDATE_PRIVACY_NOTICE = 'UPDATE_PRIVACY_NOTICE';
